import dlt
import os
import logging
import requests
import json
import time
from typing import Iterator
import pandas as pd
from pyspark.sql.functions import col, current_timestamp, input_file_name, struct
from pyspark.sql.types import StructType, StructField, StringType, DoubleType
from pyspark.sql.functions import pandas_udf

logger = logging.getLogger("atphobia22_dlt_pipeline")

# =====================================================================
# 1. BRONZE LAYER: Schema-Enforced Event Ingestion
# =====================================================================

@dlt.table(
    name="mcat_ras_raw",
    comment="Inbound parameters generated by ATphobia22/mcat-ras structural scan tools."
)
def mcat_ras_raw():
    return (
        spark.readStream.format("cloudFiles")
        .option("cloudFiles.format", "json")
        .option("cloudFiles.inferColumnTypes", "true")
        .option("cloudFiles.schemaEvolutionMode", "rescue")
        .load("/mnt/flood-models/landing/mcat_outputs/")
        .withColumn("ingested_at", current_timestamp())
        .withColumn("input_file_origin", input_file_name())
    )

@dlt.table(
    name="gauge_timedb_raw",
    comment="Time-series logs matching ATphobia22/timedb analytical tables."
)
def gauge_timedb_raw():
    return (
        spark.readStream.format("cloudFiles")
        .option("cloudFiles.format", "parquet")
        .load("/mnt/flood-models/landing/gauge_timedb/")
    )

# =====================================================================
# 2. SILVER LAYER: Data Cleansing using ATphobia22 Constraints
# =====================================================================

@dlt.table(
    name="validated_models",
    comment="Spatially clean models evaluated via rgis expectations. Drops invalid paths."
)
@dlt.expect_or_drop("has_valid_source_path", "geometry_file_path IS NOT NULL AND length(geometry_file_path) > 0")
@dlt.expect_or_drop("has_spatial_reference", "is_geospatial_referenced = true OR projection_epsg IS NOT NULL")
def validated_models():
    return (
        dlt.read_stream("mcat_ras_raw")
        .select(
            col("project_name").alias("model_id"),
            col("geometry_file_path"),
            col("projection_epsg").cast("int"),
            col("simulation_plan"),
            col("ingested_at")
        )
        .dropDuplicates(["model_id", "geometry_file_path"])
    )

@dlt.table(
    name="interpolated_flow_series",
    comment="Linearized sensor values bounding flow scales for timedb blocks."
)
@dlt.expect_or_drop("physically_possible_flow", "flow_cfs >= 0.0 AND flow_cfs <= 1500000.0")
@dlt.expect_or_fail("valid_gauge_identifier", "gauge_id IS NOT NULL")
def interpolated_flow_series():
    return (
        dlt.read_stream("gauge_timedb_raw")
        .select(
            col("gauge_id").cast("string"),
            col("timestamp").cast("timestamp"),
            col("flow_cfs").cast("double")
        )
    )

# =====================================================================
# GOLD LAYER: Digital Twin & OS Context Simulation Execution
# =====================================================================
execution_schema = StructType([
    StructField("status", StringType(), True),
    StructField("raster_destination", StringType(), True),
    StructField("township_intersect_count", StringType(), True),
    StructField("execution_latency_sec", DoubleType(), True)
])

def send_chat_alert_with_telemetry(status: str, model_id: str, details: str, latency: float = None):
    """Dispatches a structured operational notification with embedded dl-benchmark telemetry."""
    webhook_url = os.environ.get("NOTIFICATION_WEBHOOK_URL")
    if not webhook_url:
        return
        
    emoji = "✅" if status == "SUCCESS" else "🚨"
    title = f"{emoji} ATphobia22 Pipeline Run: {status}"
    
    telemetry_block = ""
    if latency:
        telemetry_block = (
            f"\n*📊 DL-Benchmark Metrics:*\n"
            f"• Processing Time: `{latency:.3f} seconds`\n"
        )
        
    payload = {
        "text": f"*{title}*\n"
                f"*Model Identifier:* `{model_id}`\n"
                f"*Timestamp:* `{pd.Timestamp.now().isoformat()}`{telemetry_block}\n"
                f"*Log Excerpt:* ```{details[:300]}```"
    }
    
    try:
        requests.post(webhook_url, data=json.dumps(payload), headers={"Content-Type": "application/json"}, timeout=5)
    except Exception as e:
        logger.error(f"Failed to transmit pipeline telemetry notification: {str(e)}")


@pandas_udf(execution_schema)
def run_twin_simulation_pipeline(iterator: Iterator[pd.Series]) -> Iterator[pd.DataFrame]:
    """
    Executes deep geospatial manipulations using compiled ATphobia22 modules,
    cross-referencing flooding output directly with Point Township municipal infrastructure layouts.
    """
    import rgis
    import dl_benchmark
    import tucker_os
    import point_township_digital_twin
    
    for parameters_series in iterator:
        results = []
        for params in parameters_series:
            model_id = params.get("model_id")
            path = params.get("geometry_file_path")
            epsg = params.get("projection_epsg")
            
            output_dir = f"/dbfs/mnt/flood-models/gold/rasters/{model_id}/"
            os.makedirs(output_dir, exist_ok=True)
            
            with tucker_os.VirtualContext(memory_limit_mb=4096) as ctx:
                tracer = dl_benchmark.Tracer(name=f"twin_simulation_{model_id}")
                tracer.start()
                
                try:
                    clean_path = str(path).replace("dbfs:", "/dbfs")
                    spatial_ctx = rgis.load_geometry(clean_path, crs=f"EPSG:{int(epsg)}")
                    raster_path = spatial_ctx.generate_inundation_grid(output_path=output_dir)
                    
                    township_twin = point_township_digital_twin.LoadWorkspace(projection=int(epsg))
                    impact_report = township_twin.overlay_flood_matrix(raster_source=raster_path)
                    intersect_count = len(impact_report.get_impacted_structures())
                    
                    tracer.stop()
                    latency = float(tracer.get_latency_seconds())
                    
                    send_chat_alert_with_telemetry(
                        "SUCCESS", model_id, 
                        f"Depth grid written successfully to destination bucket path: {raster_path}",
                        latency=latency
                    )
                    
                    results.append({
                        "status": "SUCCESS",
                        "raster_destination": raster_path,
                        "township_intersect_count": str(intersect_count),
                        "execution_latency_sec": latency
                    })
                except Exception as ex:
                    tracer.stop()
                    latency = float(tracer.get_latency_seconds())
                    
                    send_chat_alert_with_telemetry("CRITICAL_FAILURE", model_id, str(ex), latency=latency)
                    
                    results.append({
                        "status": "TWIN_SIMULATION_ERROR",
                        "raster_destination": None,
                        "township_intersect_count": "0",
                        "execution_latency_sec": latency
                    })
        yield pd.DataFrame(results)

@dlt.table(
    name="flood_inundation_raster_catalog",
    comment="Completed analytical catalog mapping your custom digital twin infrastructure simulations."
)
@dlt.expect_or_drop("simulation_completed", "execution_result.status = 'SUCCESS'")
def flood_inundation_raster_catalog():
    models_df = dlt.read("validated_models")
    flows_df = dlt.read("interpolated_flow_series")
    
    joined_df = models_df.join(flows_df, models_df.model_id == flows_df.gauge_id, "inner")
    
    return joined_df.withColumn(
        "execution_result",
        run_twin_simulation_pipeline(
            struct(
                col("model_id"),
                col("geometry_file_path"),
                col("projection_epsg")
            )
        )
    ).select(
        "model_id",
        "timestamp",
        "flow_cfs",
        "execution_result.status",
        "execution_result.raster_destination",
        "execution_result.township_intersect_count",
        "execution_result.execution_latency_sec",
        current_timestamp().alias("cataloged_at")
    )
