replicaCount: 3
image:
  repository: harbor.tucker.gov/citadel/gateway
  pullPolicy: IfNotPresent
  tag: "32.1.0"
service:
  type: ClusterIP
  port: 8000
resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 512Mi
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
env:
  oidcJwksUri: "https://idp.tucker.gov/.well-known/jwks.json"
  allowedOrigins: '["https://twin.tucker.gov","https://dashboard.tucker.gov"]'
  logLevel: "INFO"
  pythonPath: "/app"
